INSERT INTO Types (Type, Kind) VALUES ('BUILDING_PORCELAIN_TOWER', 'KIND_BUILDING');

INSERT INTO Buildings (BuildingType, Name, Description, PrereqTech, Cost, AdvisorType, MaxWorldInstances, IsWonder, RequiresPlacement, Quote, AdjacentDistrict)
VALUES ('BUILDING_PORCELAIN_TOWER', 'LOC_BUILDING_PORCELAIN_TOWER_NAME', 'LOC_BUILDING_PORCELAIN_TOWER_DESCRIPTION', 'TECH_BANKING', 920, 'ADVISOR_CULTURE', '1', 1, 1, 'LOC_BUILDING_PORCELAIN_TOWER_QUOTE', 'DISTRICT_CITY_CENTER');